### ISSUE TITLE
关于使用JS的语法高亮的后续优化

### ISSUE THREAD

**Issue by cntanglijun** [OshotOkill/understandinges6-simplified-chinese#2]
目前代码块缺少语法高亮，可以使用这种形式的代码区块定义JS的语法高亮

```js
var helloWorld = 'Hi ~';
```

``` js
var helloWorld = 'Hi ~';
```

![image](https://cloud.githubusercontent.com/assets/13279117/18423799/dc66a8f6-78da-11e6-9746-e40e1bb98f04.png)

![image](https://cloud.githubusercontent.com/assets/13279117/18423807/fc08336e-78da-11e6-8c30-30faa172d037.png)

**Comment by OshotOkill** [comment]
@cntanglijun 非常好，这个功能以前没注意到，今天晚上我会修改它们。

**Comment by OshotOkill** [comment]
已添加高亮，此 issue 关闭
