### ISSUE TITLE
关于使用 Code Spans 

### ISSUE THREAD

**Issue by cntanglijun** [OshotOkill/understandinges6-simplified-chinese#4]
可以使用  `Code Spans`  这种形式突出一些引用的代码

这是一个 `Code Spans`

![image](https://cloud.githubusercontent.com/assets/13279117/18481150/b8762e74-7a0d-11e6-8712-376f1dbe39c1.png)

**Comment by OshotOkill** [comment]
是这样，当初未给段落中添加 code span 主要是它的阅读效果不佳，因为段落中有其它不是代码的英文词条，导致看上去比较混乱，而且字体没有发生太大变化的情况下还会缩小字号。

**Comment by cntanglijun** [comment]
:ok_hand: 好的
